//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFMS_S.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/eOA_WebService/Service1", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_Value", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReturnRework_Value(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_Value", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReturnRework_ValueAsync(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_ByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnRework_ByID(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_ByID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnRework_ByIDAsync(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_ByWorkSerial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnRework_ByWorkSerial(string Work_Serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnRework_ByWorkSerial", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnRework_ByWorkSerialAsync(string Work_Serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_Value", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReturnQDR_Value(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_Value", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReturnQDR_ValueAsync(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_Ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnQDR_Ta(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_Ta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_TaAsync(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_KaoQin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RMA_KaoQin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_KaoQin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RMA_KaoQinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_KaoQin_New", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RMA_KaoQin_New(string var_dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_KaoQin_New", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RMA_KaoQin_NewAsync(string var_dept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RMA_User();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/RMA_User", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RMA_UserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_ePRData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_ePRData(string Work_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_ePRData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_ePRDataAsync(string Work_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_eOAUserData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_eOAUserDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_eOAUserName(string Var_Hrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Get_eOAUserNameAsync(string Var_Hrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_New_Ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnQDR_New_Ta(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_New_Ta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_New_TaAsync(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_CTOS_Ta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnQDR_CTOS_Ta(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnQDR_CTOS_Ta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_CTOS_TaAsync(string Jizhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnOverdueGoods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnOverdueGoods(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnOverdueGoods", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnOverdueGoodsAsync(int Taskid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnKQS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReturnKQS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/ReturnKQS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReturnKQSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetUserByCardId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserByCardId(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetUserByCardId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUserByCardIdAsync(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetUserByCardId_IC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserByCardId_IC(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetUserByCardId_IC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUserByCardId_ICAsync(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_Human_Resources", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_Human_Resources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_Human_Resources", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_Human_ResourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_HumanQuit_Statistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_HumanQuit_Statistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_HumanQuit_Statistics", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_HumanQuit_StatisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetATCUserByCardId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetATCUserByCardId(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetATCUserByCardId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetATCUserByCardIdAsync(string cardid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_eOAUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_eOAUser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_eOAUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOAUserForDCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GeteOAUserForDCC(string Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOAUserForDCC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GeteOAUserForDCCAsync(string Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOAUserManagerForDCC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GeteOAUserManagerForDCC(string Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOAUserManagerForDCC", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GeteOAUserManagerForDCCAsync(string Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForESOP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNewQDR_ForESOP(string Var_Fac, string Process_Monitoring, string MACHINE_MODEL, string Var_material, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForESOP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForESOPAsync(string Var_Fac, string Process_Monitoring, string MACHINE_MODEL, string Var_material, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForIMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomerComplaintForm_ForIMS(string Var_SubOrder, string Process_Monitoring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForIMS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForIMSAsync(string Var_SubOrder, string Process_Monitoring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForIMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNewQDR_ForIMS(string MACHINE_MODEL, string Process_Monitoring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForIMS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForIMSAsync(string MACHINE_MODEL, string Process_Monitoring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForFQC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNewQDR_ForFQC(string MACHINE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForFQC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForFQCAsync(string MACHINE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForNPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNewQDR_ForNPI(string Var_material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetNewQDR_ForNPI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForNPIAsync(string Var_material);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOA_Group", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GeteOA_Group();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GeteOA_Group", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GeteOA_GroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_KQUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_KQUserData(string var_Hrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/Get_KQUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_KQUserDataAsync(string var_Hrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForESOP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomerComplaintForm_ForESOP(string MACHINE_MODEL, string Process_Monitoring, string Var_SubOrder, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForESOP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForESOPAsync(string MACHINE_MODEL, string Process_Monitoring, string Var_SubOrder, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomerComplaintForm(string MACHINE_MODEL, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintFormAsync(string MACHINE_MODEL, System.DateTime bt, System.DateTime et);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForFQC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustomerComplaintForm_ForFQC(string MACHINE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetCustomerComplaintForm_ForFQC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForFQCAsync(string MACHINE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetChassis_ES_Bug", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetChassis_ES_Bug(string Var_Liaohao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetChassis_ES_Bug", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetChassis_ES_BugAsync(string Var_Liaohao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetChassis_ES_Bug_New", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetChassis_ES_Bug_New(string Var_Liaohao, string Var_Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eOA_WebService/Service1/GetChassis_ES_Bug_New", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetChassis_ES_Bug_NewAsync(string Var_Liaohao, string Var_Status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PFMS_S.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PFMS_S.ServiceReference1.Service1Soap>, PFMS_S.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReturnRework_Value(int Taskid) {
            return base.Channel.ReturnRework_Value(Taskid);
        }
        
        public System.Threading.Tasks.Task<string> ReturnRework_ValueAsync(int Taskid) {
            return base.Channel.ReturnRework_ValueAsync(Taskid);
        }
        
        public System.Data.DataTable ReturnRework_ByID(int Taskid) {
            return base.Channel.ReturnRework_ByID(Taskid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnRework_ByIDAsync(int Taskid) {
            return base.Channel.ReturnRework_ByIDAsync(Taskid);
        }
        
        public System.Data.DataTable ReturnRework_ByWorkSerial(string Work_Serial) {
            return base.Channel.ReturnRework_ByWorkSerial(Work_Serial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnRework_ByWorkSerialAsync(string Work_Serial) {
            return base.Channel.ReturnRework_ByWorkSerialAsync(Work_Serial);
        }
        
        public string ReturnQDR_Value(int Taskid) {
            return base.Channel.ReturnQDR_Value(Taskid);
        }
        
        public System.Threading.Tasks.Task<string> ReturnQDR_ValueAsync(int Taskid) {
            return base.Channel.ReturnQDR_ValueAsync(Taskid);
        }
        
        public System.Data.DataTable ReturnQDR_Ta(string Jizhong) {
            return base.Channel.ReturnQDR_Ta(Jizhong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_TaAsync(string Jizhong) {
            return base.Channel.ReturnQDR_TaAsync(Jizhong);
        }
        
        public System.Data.DataTable RMA_KaoQin() {
            return base.Channel.RMA_KaoQin();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RMA_KaoQinAsync() {
            return base.Channel.RMA_KaoQinAsync();
        }
        
        public System.Data.DataTable RMA_KaoQin_New(string var_dept) {
            return base.Channel.RMA_KaoQin_New(var_dept);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RMA_KaoQin_NewAsync(string var_dept) {
            return base.Channel.RMA_KaoQin_NewAsync(var_dept);
        }
        
        public System.Data.DataTable RMA_User() {
            return base.Channel.RMA_User();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RMA_UserAsync() {
            return base.Channel.RMA_UserAsync();
        }
        
        public System.Data.DataTable Get_ePRData(string Work_ID) {
            return base.Channel.Get_ePRData(Work_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_ePRDataAsync(string Work_ID) {
            return base.Channel.Get_ePRDataAsync(Work_ID);
        }
        
        public System.Data.DataTable Get_eOAUserData() {
            return base.Channel.Get_eOAUserData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_eOAUserDataAsync() {
            return base.Channel.Get_eOAUserDataAsync();
        }
        
        public string Get_eOAUserName(string Var_Hrid) {
            return base.Channel.Get_eOAUserName(Var_Hrid);
        }
        
        public System.Threading.Tasks.Task<string> Get_eOAUserNameAsync(string Var_Hrid) {
            return base.Channel.Get_eOAUserNameAsync(Var_Hrid);
        }
        
        public System.Data.DataTable ReturnQDR_New_Ta(string Jizhong) {
            return base.Channel.ReturnQDR_New_Ta(Jizhong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_New_TaAsync(string Jizhong) {
            return base.Channel.ReturnQDR_New_TaAsync(Jizhong);
        }
        
        public System.Data.DataTable ReturnQDR_CTOS_Ta(string Jizhong) {
            return base.Channel.ReturnQDR_CTOS_Ta(Jizhong);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnQDR_CTOS_TaAsync(string Jizhong) {
            return base.Channel.ReturnQDR_CTOS_TaAsync(Jizhong);
        }
        
        public System.Data.DataTable ReturnOverdueGoods(int Taskid) {
            return base.Channel.ReturnOverdueGoods(Taskid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnOverdueGoodsAsync(int Taskid) {
            return base.Channel.ReturnOverdueGoodsAsync(Taskid);
        }
        
        public System.Data.DataTable ReturnKQS() {
            return base.Channel.ReturnKQS();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReturnKQSAsync() {
            return base.Channel.ReturnKQSAsync();
        }
        
        public System.Data.DataTable GetUserByCardId(string cardid) {
            return base.Channel.GetUserByCardId(cardid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUserByCardIdAsync(string cardid) {
            return base.Channel.GetUserByCardIdAsync(cardid);
        }
        
        public System.Data.DataTable GetUserByCardId_IC(string cardid) {
            return base.Channel.GetUserByCardId_IC(cardid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUserByCardId_ICAsync(string cardid) {
            return base.Channel.GetUserByCardId_ICAsync(cardid);
        }
        
        public System.Data.DataTable Get_Human_Resources() {
            return base.Channel.Get_Human_Resources();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_Human_ResourcesAsync() {
            return base.Channel.Get_Human_ResourcesAsync();
        }
        
        public System.Data.DataTable Get_HumanQuit_Statistics() {
            return base.Channel.Get_HumanQuit_Statistics();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_HumanQuit_StatisticsAsync() {
            return base.Channel.Get_HumanQuit_StatisticsAsync();
        }
        
        public System.Data.DataTable GetATCUserByCardId(string cardid) {
            return base.Channel.GetATCUserByCardId(cardid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetATCUserByCardIdAsync(string cardid) {
            return base.Channel.GetATCUserByCardIdAsync(cardid);
        }
        
        public System.Data.DataTable Get_eOAUser() {
            return base.Channel.Get_eOAUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_eOAUserAsync() {
            return base.Channel.Get_eOAUserAsync();
        }
        
        public System.Data.DataTable GeteOAUserForDCC(string Account) {
            return base.Channel.GeteOAUserForDCC(Account);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GeteOAUserForDCCAsync(string Account) {
            return base.Channel.GeteOAUserForDCCAsync(Account);
        }
        
        public string GeteOAUserManagerForDCC(string Account) {
            return base.Channel.GeteOAUserManagerForDCC(Account);
        }
        
        public System.Threading.Tasks.Task<string> GeteOAUserManagerForDCCAsync(string Account) {
            return base.Channel.GeteOAUserManagerForDCCAsync(Account);
        }
        
        public System.Data.DataTable GetNewQDR_ForESOP(string Var_Fac, string Process_Monitoring, string MACHINE_MODEL, string Var_material, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetNewQDR_ForESOP(Var_Fac, Process_Monitoring, MACHINE_MODEL, Var_material, bt, et);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForESOPAsync(string Var_Fac, string Process_Monitoring, string MACHINE_MODEL, string Var_material, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetNewQDR_ForESOPAsync(Var_Fac, Process_Monitoring, MACHINE_MODEL, Var_material, bt, et);
        }
        
        public System.Data.DataTable GetCustomerComplaintForm_ForIMS(string Var_SubOrder, string Process_Monitoring) {
            return base.Channel.GetCustomerComplaintForm_ForIMS(Var_SubOrder, Process_Monitoring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForIMSAsync(string Var_SubOrder, string Process_Monitoring) {
            return base.Channel.GetCustomerComplaintForm_ForIMSAsync(Var_SubOrder, Process_Monitoring);
        }
        
        public System.Data.DataTable GetNewQDR_ForIMS(string MACHINE_MODEL, string Process_Monitoring) {
            return base.Channel.GetNewQDR_ForIMS(MACHINE_MODEL, Process_Monitoring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForIMSAsync(string MACHINE_MODEL, string Process_Monitoring) {
            return base.Channel.GetNewQDR_ForIMSAsync(MACHINE_MODEL, Process_Monitoring);
        }
        
        public System.Data.DataTable GetNewQDR_ForFQC(string MACHINE_MODEL) {
            return base.Channel.GetNewQDR_ForFQC(MACHINE_MODEL);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForFQCAsync(string MACHINE_MODEL) {
            return base.Channel.GetNewQDR_ForFQCAsync(MACHINE_MODEL);
        }
        
        public System.Data.DataTable GetNewQDR_ForNPI(string Var_material) {
            return base.Channel.GetNewQDR_ForNPI(Var_material);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetNewQDR_ForNPIAsync(string Var_material) {
            return base.Channel.GetNewQDR_ForNPIAsync(Var_material);
        }
        
        public System.Data.DataTable GeteOA_Group() {
            return base.Channel.GeteOA_Group();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GeteOA_GroupAsync() {
            return base.Channel.GeteOA_GroupAsync();
        }
        
        public System.Data.DataTable Get_KQUserData(string var_Hrid) {
            return base.Channel.Get_KQUserData(var_Hrid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_KQUserDataAsync(string var_Hrid) {
            return base.Channel.Get_KQUserDataAsync(var_Hrid);
        }
        
        public System.Data.DataTable GetCustomerComplaintForm_ForESOP(string MACHINE_MODEL, string Process_Monitoring, string Var_SubOrder, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetCustomerComplaintForm_ForESOP(MACHINE_MODEL, Process_Monitoring, Var_SubOrder, bt, et);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForESOPAsync(string MACHINE_MODEL, string Process_Monitoring, string Var_SubOrder, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetCustomerComplaintForm_ForESOPAsync(MACHINE_MODEL, Process_Monitoring, Var_SubOrder, bt, et);
        }
        
        public System.Data.DataTable GetCustomerComplaintForm(string MACHINE_MODEL, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetCustomerComplaintForm(MACHINE_MODEL, bt, et);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintFormAsync(string MACHINE_MODEL, System.DateTime bt, System.DateTime et) {
            return base.Channel.GetCustomerComplaintFormAsync(MACHINE_MODEL, bt, et);
        }
        
        public System.Data.DataTable GetCustomerComplaintForm_ForFQC(string MACHINE_MODEL) {
            return base.Channel.GetCustomerComplaintForm_ForFQC(MACHINE_MODEL);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCustomerComplaintForm_ForFQCAsync(string MACHINE_MODEL) {
            return base.Channel.GetCustomerComplaintForm_ForFQCAsync(MACHINE_MODEL);
        }
        
        public System.Data.DataTable GetChassis_ES_Bug(string Var_Liaohao) {
            return base.Channel.GetChassis_ES_Bug(Var_Liaohao);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetChassis_ES_BugAsync(string Var_Liaohao) {
            return base.Channel.GetChassis_ES_BugAsync(Var_Liaohao);
        }
        
        public System.Data.DataTable GetChassis_ES_Bug_New(string Var_Liaohao, string Var_Status) {
            return base.Channel.GetChassis_ES_Bug_New(Var_Liaohao, Var_Status);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetChassis_ES_Bug_NewAsync(string Var_Liaohao, string Var_Status) {
            return base.Channel.GetChassis_ES_Bug_NewAsync(Var_Liaohao, Var_Status);
        }
    }
}
